"""Offline sound renderer for Mountain Goat Killer: The Last Bell.

Usage (from the project root):
    python3 tools/audio/render.py [--only NAME ...] [--out assets/audio/generated]

Renders every sound in registry.SOUNDS plus beds/music (ambience.py, music.py)
into 44.1 kHz 16-bit WAV (one-shots) or Ogg Vorbis (long material) files. Every
sound is seeded from its name, so output is reproducible. Also writes
manifest.json (name, files, bus, format, peak, rms, duration) which the game's
tests read.
"""
import argparse
import json
import os
import subprocess
import sys
import wave

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from dsp import SR, finish, rng_for  # noqa: E402
from registry import SOUNDS  # noqa: E402


def write_wav(path, x):
	x = np.atleast_2d(x.T).T if x.ndim == 1 else x
	pcm = np.clip(np.round(x * 32767.0), -32768, 32767).astype("<i2")
	with wave.open(path, "wb") as fh:
		fh.setnchannels(pcm.shape[1])
		fh.setsampwidth(2)
		fh.setframerate(SR)
		fh.writeframes(pcm.tobytes())


def write_ogg(path, x, bitrate="192k"):
	"""Ogg Vorbis via ffmpeg's native encoder (this build has no libvorbis; it only
	encodes stereo, so mono sources are written as dual-mono)."""
	tmp = path + ".tmp.wav"
	write_wav(tmp, x)
	subprocess.run(["ffmpeg", "-loglevel", "error", "-y", "-i", tmp, "-c:a", "vorbis", "-strict", "-2", "-ac", "2", "-b:a", bitrate, path], check=True)
	os.remove(tmp)


def stats(x):
	x = np.atleast_2d(x.T).T if x.ndim == 1 else x
	peak = float(np.max(np.abs(x)))
	rms = float(np.sqrt(np.mean(x ** 2)))
	return peak, rms


def render_named(out_dir, only=None):
	entries = {}
	for name, (fn, variants, peak_db, fmt, bus) in SOUNDS.items():
		if only and name not in only:
			continue
		files = []
		info = []
		for v in range(variants):
			rng = rng_for("%s:%d" % (name, v))
			x = fn(rng, v)
			x = finish(x, peak_db)
			stem = name if variants == 1 else "%s_%02d" % (name, v)
			path = os.path.join(out_dir, stem + "." + fmt)
			if fmt == "wav":
				write_wav(path, x)
			else:
				write_ogg(path, x)
			peak, rms = stats(x)
			info.append({"peak": peak, "rms": rms, "seconds": len(x) / SR})
			files.append(stem + "." + fmt)
		entries[name] = {"files": files, "bus": bus, "fmt": fmt, "target_peak_db": peak_db, "clips": info}
		print("%-20s %d clip(s) %-4s peak %.2f dB, %.2f s" % (name, variants, fmt, 20 * np.log10(max(info[0]["peak"], 1e-9)), info[0]["seconds"]))
	return entries


def write_bank(entries, path):
	"""Emit scripts/audio_bank.gd so the game knows every generated file without
	scanning directories (which does not work in exported builds)."""
	here = os.path.dirname(os.path.abspath(__file__))
	with open(os.path.join(here, "voice_manifest.json")) as fh:
		voices = json.load(fh)
	lines = ["class_name AudioBank", "extends RefCounted",
		"## GENERATED by tools/audio/render.py. Do not edit; re-run the renderer.",
		"## SOUNDS maps a sound name to its clip files (under assets/audio/generated/),",
		"## the mix bus it plays on and whether it is a loop. VOICE maps a voice line",
		"## id (assets/audio/voice/<id>.ogg) to its speaker.", "",
		"const SOUNDS := {"]
	for name in sorted(entries):
		e = entries[name]
		files = ", ".join('"%s"' % f for f in e["files"])
		lines.append('\t"%s": {"files": [%s], "bus": "%s", "loop": %s},' % (name, files, e["bus"], "true" if e.get("loop") else "false"))
	lines += ["}", "", "const VOICE := {"]
	for entry in voices["lines"]:
		lines.append('\t"%s": "%s",' % (entry["id"], entry["speaker"]))
	lines += ["}", ""]
	with open(path, "w") as fh:
		fh.write("\n".join(lines))


def main():
	ap = argparse.ArgumentParser()
	ap.add_argument("--only", nargs="*")
	ap.add_argument("--out", default="assets/audio/generated")
	ap.add_argument("--skip-beds", action="store_true", help="skip ambience beds and music")
	ap.add_argument("--only-music", action="store_true", help="render only ambience beds and music")
	args = ap.parse_args()
	os.makedirs(args.out, exist_ok=True)
	entries = {} if args.only_music else render_named(args.out, args.only)
	if (not args.only or args.only_music) and not args.skip_beds:
		import ambience
		import music
		entries.update(ambience.render_all(args.out))
		entries.update(music.render_all(args.out))
	manifest_path = os.path.join(args.out, "manifest.json")
	if (args.only or args.only_music) and os.path.exists(manifest_path):
		with open(manifest_path) as fh:
			merged = json.load(fh)
		merged.update(entries)
		entries = merged
	with open(manifest_path, "w") as fh:
		json.dump(entries, fh, indent=1, sort_keys=True)
	if not args.only and not args.skip_beds and not args.only_music:
		# A full render owns the directory: drop clips (and their Godot .import files)
		# that no longer belong to any sound, e.g. after a wav -> ogg change.
		keep = {"manifest.json"}
		for entry in entries.values():
			keep.update(entry["files"])
			keep.update(f + ".import" for f in entry["files"])
		for stale in os.listdir(args.out):
			if stale not in keep:
				os.remove(os.path.join(args.out, stale))
		write_bank(entries, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "scripts", "audio_bank.gd"))
	print("wrote", manifest_path, len(entries), "sounds")


if __name__ == "__main__":
	main()
